plugins:
  - jekyll-target-blank

# Basic Information 
title: Hui-Po Wang
position: Ph.D Student
affiliation: CISPA – Helmholtz Center for Information Security
affiliation_link: /
affiliation_logo: /assets/img/cispa-long-logo.svg
email: huipowang24 (at) gmail.com

# Search Engine Optimization (SEO)
keywords: Hui-Po Wang, huipowang, hpwang, wanghuipo, wanghp, Wang Hui-Po
google_analytics_id: G-R6CK2SVZWC
canonical: https://hui-po-wang.github.io
description: Hui-Po Wang is a Ph.D student at CISPA, specializing in efficient and privacy-preserving machine learning.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=UAnfs8UAAAAJ&hl=zh-TW
github_link: https://github.com/hui-po-wang
linkedin: https://www.linkedin.com/in/hui-po-wang-7a0158137/
twitter: https://x.com/HuiPoWang1

# Images 
avatar: /assets/img/avatar_small.png
favicon: /assets/img/favicon.ico
favicon_dark: /assets/img/favicon.ico

# Footnotes
footnote: 
footnote_link: 

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 3Hr3NcXEXINFd-eWMQ-eiYFhCAJ2zjVn2R2ivv_MTK8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
